# Site settings
title: Rod Machen
email: mail@rodmachen.com
description: > # this means to ignore newlines until "baseurl:"
  Rod Machen's writings on technology and code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://code.rodmachen.com" # the base hostname & protocol for your site
twitter_username: rod_machen

# Build settings
markdown: kramdown

permalink: /:title/

paginate: 10
paginate_path: "/page:num/"

exclude: 
 - s3_website.yml