# Site settings
title: Rod Machen
email: mail@rodmachen.com
description: > # this means to ignore newlines until "baseurl:"
  Rod Machen's writings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rodmachen.com" # the base hostname & protocol for your site
twitter_username: rodmachen

# Build settings
markdown: kramdown

permalink: /:categories/:title/

paginate: 20
paginate_path: "/writing/page:num/"