description: Rod Machen on the web.

author:
  name: Rod Machen
  email: mail@rodmachen.com

# Exclude directories and/or files from the conversion.
# Grunt moves image files and the styles/scripts directories.
exclude: ['node_modules', 'styles', 'scripts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: /:categories/:title/

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: false

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
# paginate: 5
# paginate_path: 'page:num'

# Markdown library
# markdown: redcarpet
markdown: kramdown
# markdown: rdiscount
# Markdown library options
# redcarpet:
  # extensions: ['fenced_code_blocks', 'smart']

# Use Pygments to highlight code blocks
highlighter: pygments
